version: '2'
services:
    portfoliomanager:
          container_name: portfoliomanager_web
          image: manthasriram/portfoliomanager:latest
          ports:
            - "80:8080"
    mongodb:
         container_name: mongodb
         image: mongo:latest
         volumes: /opt/mongodb:/data/db
