version: '2'
services:
    portfoliomanager-mongodb:
        container_name: portfoliomanager-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb portfoliomanager-mongodb-config
    portfoliomanager-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    portfoliomanager-mongodb-config:
        image: mongo:3.2.3
        container_name: portfoliomanager-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
