version: '2'
services:
    portfoliomanager-mongodb:
        container_name: portfoliomanager-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/portfoliomanager/mongodb/:/data/db/
